/**
 * scripts/naming-lint/install-hook.mjs
 *
 * Installs a Node-based pre-commit hook that runs naming-lint on every commit.
 * Cross-platform (Windows / macOS / Linux) since it uses Node.
 *
 * Usage:
 *   node scripts/naming-lint/install-hook.mjs install    # install the hook
 *   node scripts/naming-lint/install-hook.mjs uninstall  # remove the hook
 *   node scripts/naming-lint/install-hook.mjs --ci-comment docs scripts  # CI use: build PR comment
 *
 * After install, every `git commit` runs:
 *   node scripts/naming-lint/index.mjs --json docs scripts > /tmp/lint.json
 * If violations found, commit is rejected with a summary.
 *
 * To bypass: `git commit --no-verify -m "..."`
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..');
const HOOKS_DIR = join(REPO_ROOT, '.git', 'hooks');
const HOOK_PATH = join(HOOKS_DIR, 'pre-commit');

// ---------------------------------------------------------------------------
// Hook script content
// ---------------------------------------------------------------------------

const HOOK_SCRIPT = `#!/usr/bin/env node
// Auto-generated by scripts/naming-lint/install-hook.mjs
// Do not edit by hand. To uninstall, run:
//   node scripts/naming-lint/install-hook.mjs uninstall

import { execSync } from 'node:child_process';
import { readFileSync } from 'node:fs';

const ROOTS = (process.env.NAMING_LINT_ROOTS ?? 'docs,scripts').split(',').map(s => s.trim()).filter(Boolean);
const LINT = 'node scripts/naming-lint/index.mjs --json ' + ROOTS.join(' ');

let stdout = '';
try {
  stdout = execSync(LINT, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] });
} catch (err) {
  // Lint failed (exit 1). Parse JSON, show errors.
  let report = null;
  try { report = JSON.parse(err.stdout ?? ''); } catch {}

  console.error('');
  console.error('naming-lint: COMMIT BLOCKED');
  console.error('='.repeat(60));
  if (report && report.violations) {
    console.error('Found ' + report.violationCount + ' violation(s):');
    for (const v of report.violations) {
      console.error('  ' + v.path + ' [' + v.rule + ']');
      console.error('      ' + v.message);
    }
  } else {
    console.error('Lint failed (output below):');
    console.error(stdout || err.message);
  }
  console.error('='.repeat(60));
  console.error('Bypass with: git commit --no-verify');
  process.exit(1);
}

// Pass
process.exit(0);
`;

// ---------------------------------------------------------------------------
// Install / uninstall / ci-comment
// ---------------------------------------------------------------------------

function install() {
  if (!existsSync(join(REPO_ROOT, '.git'))) {
    console.error('ERROR: .git directory not found. Run from repo root.');
    process.exit(1);
  }
  if (!existsSync(HOOKS_DIR)) {
    mkdirSync(HOOKS_DIR, { recursive: true });
  }
  writeFileSync(HOOK_PATH, HOOK_SCRIPT, { mode: 0o755 });
  console.log('OK: pre-commit hook installed at .git/hooks/pre-commit');
  console.log('    Runs: node scripts/naming-lint/index.mjs --json ' + (process.env.NAMING_LINT_ROOTS ?? 'docs scripts'));
  console.log('    Bypass: git commit --no-verify');
}

function uninstall() {
  if (existsSync(HOOK_PATH)) {
    // Use execSync for cross-platform rm
    try {
      execSync(`node -e "require('fs').unlinkSync('${HOOK_PATH.replace(/\\\\/g, '/')}', () => {})"`, { stdio: 'ignore' });
    } catch {}
    // Fallback: simple rm via node
    try {
      const fs = require('node:fs');
      fs.unlinkSync(HOOK_PATH);
    } catch {}
    console.log('OK: pre-commit hook removed');
  } else {
    console.log('No hook to remove');
  }
}

/**
 * Build a PR comment body from a naming-lint JSON report.
 * Usage: --ci-comment <roots...>
 *   1. Runs `node scripts/naming-lint/index.mjs --json <roots>`
 *   2. Outputs Markdown to stdout (for posting as a PR comment)
 */
function buildCiComment() {
  // Args after the first are roots
  const roots = process.argv.slice(3);
  if (roots.length === 0) {
    console.error('Usage: --ci-comment <roots...>');
    process.exit(1);
  }
  let stdout = '';
  let exitCode = 0;
  try {
    stdout = execSync(`node ${join(REPO_ROOT, 'scripts', 'naming-lint', 'index.mjs')} --json ${roots.join(' ')}`, { encoding: 'utf8' });
  } catch (err) {
    stdout = err.stdout ?? '';
    exitCode = err.status ?? 1;
  }
  let report;
  try { report = JSON.parse(stdout); } catch {
    console.error('Could not parse naming-lint output:');
    console.error(stdout);
    process.exit(1);
  }

  const lines = [];
  if (report.passed) {
    lines.push('### ✅ naming-lint passed', '');
    lines.push('All ' + report.roots.length + ' root(s) clean: `' + report.roots.join('`, `') + '`');
  } else {
    lines.push('### ❌ naming-lint failed', '');
    lines.push('**' + report.violationCount + ' violation(s)** in `' + report.roots.join('`, `') + '`', '');
    lines.push('| File | Rule | Message |');
    lines.push('| --- | --- | --- |');
    for (const v of report.violations.slice(0, 50)) {
      lines.push('| `' + v.path + '` | `' + v.rule + '` | ' + v.message + ' |');
    }
    if (report.violations.length > 50) {
      lines.push('| ... | ... | (' + (report.violations.length - 50) + ' more) |');
    }
  }
  lines.push('');
  lines.push('See [`docs/style/naming-conventions.md`](docs/style/naming-conventions.md) for the rules.');
  console.log(lines.join('\n'));
  process.exit(exitCode);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const cmd = process.argv[2];
switch (cmd) {
  case 'install':   install(); break;
  case 'uninstall': uninstall(); break;
  case '--ci-comment': buildCiComment(); break;
  default:
    console.error('Usage:');
    console.error('  install     # install pre-commit hook');
    console.error('  uninstall   # remove pre-commit hook');
    console.error('  --ci-comment <roots...>  # build PR comment from --json output');
    process.exit(1);
}